[package]
name = "fail2ban-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "6.1.1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
regex = "1.11.0"
